version: '3.8'

services:
  scraper:
    build: .
    container_name: exito_scraper
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - scraper_network

  mongo:
    image: mongo:7.0
    container_name: exito_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - scraper_network

  redis:
    image: redis:7.2-alpine
    container_name: exito_redis
    ports:
      - "6379:6379"
    networks:
      - scraper_network

  prometheus:
    image: prom/prometheus:latest
    container_name: exito_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - scraper_network

volumes:
  mongo_data:

networks:
  scraper_network:
    driver: bridge
